const pseudoList = [
  "active",
  "after",
  "before",
  "checked",
  "disabled",
  "empty",
  "enabled",
  "first-child",
  "first-letter",
  "first-line",
  "first-of-type",
  "focus",
  "hover",
  "lang",
  "last-child",
  "last-of-type",
  "link",
  "not(",
  "nth-child(",
  "nth-last-child(",
  "nth-last-of-type(",
  "nth-of-type(",
  "only-child",
  "only-of-type",
  "root",
  "target",
  "visited",
];

const propList = [
  "align-content",
  "align-items",
  "align-self",
  "all", // shorthand
  "animation", // shorthand
  "animation-delay",
  "animation-direction",
  "animation-duration",
  "animation-fill-mode",
  "animation-iteration-count",
  "animation-name",
  "animation-play-state",
  "animation-timing-function",
  "azimuth",
  "background", // shorthand
  "background-attachment",
  "background-blend-mode",
  "background-clip",
  "background-color",
  "background-image",
  "background-origin",
  "background-position",
  "background-repeat",
  "background-size",
  "border", // shorthand
  "border-bottom", // shorthand
  "border-bottom-color",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "border-bottom-style",
  "border-bottom-width",
  "border-collapse",
  "border-color", // shorthand
  "border-image", // shorthand
  "border-image-outset",
  "border-image-repeat",
  "border-image-slice",
  "border-image-source",
  "border-image-width",
  "border-left", // shorthand
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius", // shorthand
  "border-right", // shorthand
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-spacing",
  "border-style", // shorthand
  "border-top", // shorthand
  "border-top-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-top-style",
  "border-top-width",
  "border-width", // shorthand
  "bottom",
  "box-decoration-break",
  "box-shadow",
  "box-sizing",
  "break-after",
  "break-before",
  "break-inside",
  "caption-side",
  "caret-color",
  "clear",
  "clip",
  "clip-path",
  "clip-rule",
  "color",
  "color-interpolation-filters",
  "column-count",
  "column-fill",
  "column-gap",
  "column-rule",
  "column-rule-color",
  "column-rule-style",
  "column-rule-width",
  "columns",
  "column-span",
  "column-width",
  "contain",
  "content",
  "counter-increment",
  "counter-reset",
  "cue", // shorthand
  "cue-after",
  "cue-before",
  "cursor",
  "direction",
  "display",
  "elevation",
  "empty-cells",
  "filter",
  "flex", // shorthand
  "flex-basis",
  "flex-direction",
  "flex-flow",
  "flex-grow",
  "flex-shrink",
  "flex-wrap",
  "float",
  "flood-color",
  "flood-opacity",
  "font", // shorthand
  "font-family",
  "font-feature-settings",
  "font-kerning",
  "font-size",
  "font-size-adjust",
  "font-stretch",
  "font-style",
  "font-synthesis",
  "font-variant",
  "font-variant-caps",
  "font-variant-east-asian",
  "font-variant-ligatures",
  "font-variant-numeric",
  "font-variant-position",
  "font-weight",
  "gap",
  "globalcompositeoperation",
  "glyph-orientation-vertical",
  "grid", // shorthand
  "grid-area",
  "grid-auto-columns",
  "grid-auto-flow",
  "grid-auto-rows",
  "grid-column", // shorthand
  "grid-column-end",
  "grid-column-gap",
  "grid-column-start",
  "grid-gap",
  "grid-row", // shorthand
  "grid-row-end",
  "grid-row-gap",
  "grid-row-start",
  "grid-template", // shorthand
  "grid-template-areas",
  "grid-template-columns",
  "grid-template-rows",
  "hanging-punctuation",
  "height",
  "hyphens",
  "image-orientation",
  "image-rendering",
  "image-resolution",
  "isolation",
  "justify-content",
  "justify-items",
  "justify-self",
  "left",
  "letter-spacing",
  "lighting-color",
  "line-break",
  "line-height",
  "list-style", // shorthand
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "margin", // shorthand
  "margin-bottom",
  "margin-left",
  "margin-right",
  "margin-top",
  "mask", // shorthand
  "mask-border", // shorthand
  "mask-border-mode",
  "mask-border-outset",
  "mask-border-repeat",
  "mask-border-slice",
  "mask-border-source",
  "mask-border-width",
  "mask-clip",
  "mask-composite",
  "mask-image",
  "mask-mode",
  "mask-origin",
  "mask-position",
  "mask-repeat",
  "mask-size",
  "mask-type",
  "max-height",
  "max-width",
  "min-height",
  "min-width",
  "mix-blend-mode",
  "object-fit",
  "object-position",
  "opacity",
  "order",
  "orphans",
  "outline", // shorthand
  "outline-color",
  "outline-offset",
  "outline-style",
  "outline-width",
  "overflow",
  "overflow-wrap",
  "overflow-x",
  "overflow-y",
  "padding", // shorthand
  "padding-bottom",
  "padding-left",
  "padding-right",
  "padding-top",
  "page-break-after",
  "page-break-before",
  "page-break-inside",
  "pause", // shorthand
  "pause-after",
  "pause-before",
  "pitch", // shorthand
  "pitch-range",
  "place-content",
  "place-items",
  "place-self",
  "play-during",
  "position",
  "quotes",
  "resize",
  "rest", // shorthand
  "rest-after",
  "rest-before",
  "richness",
  "right",
  "row-gap",
  "scroll-margin", // shorthand
  "scroll-margin-block",
  "scroll-margin-block-end",
  "scroll-margin-block-start",
  "scroll-margin-bottom",
  "scroll-margin-inline",
  "scroll-margin-inline-end",
  "scroll-margin-inline-start",
  "scroll-margin-left",
  "scroll-margin-right",
  "scroll-margin-top",
  "scroll-padding", // shorthand
  "scroll-padding-block",
  "scroll-padding-block-end",
  "scroll-padding-block-start",
  "scroll-padding-bottom",
  "scroll-padding-inline",
  "scroll-padding-inline-end",
  "scroll-padding-inline-start",
  "scroll-padding-left",
  "scroll-padding-right",
  "scroll-padding-top",
  "scroll-snap-align",
  "scroll-snap-stop",
  "scroll-snap-type",
  "shape-image-threshold",
  "shape-margin",
  "shape-outside",
  "speak",
  "speak-as",
  "speak-header",
  "speak-numeral",
  "speak-punctuation",
  "speech-rate",
  "stress",
  "table-layout",
  "tab-size",
  "text-align",
  "text-align-all",
  "text-align-last",
  "text-combine-upright",
  "text-decoration", // shorthand
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-style",
  "text-emphasis", // shorthand
  "text-emphasis-color",
  "text-emphasis-position",
  "text-emphasis-style",
  "text-indent",
  "text-justify",
  "text-orientation",
  "text-overflow",
  "text-shadow",
  "text-transform",
  "text-underline-position",
  "top",
  "transform",
  "transform-box",
  "transform-origin",
  "transition", // shorthand
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
  "unicode-bidi",
  "vertical-align",
  "visibility",
  "voice-balance",
  "voice-duration",
  "voice-family",
  "voice-pitch",
  "voice-range",
  "voice-rate",
  "voice-stress",
  "voice-volume",
  "volume",
  "white-space",
  "widows",
  "width",
  "will-change",
  "word-break",
  "word-spacing",
  "word-wrap",
  "writing-mode",
  "z-index",
];

const base = 36;
export const NONE = "----";

/**
 * @arg {string[]} list
 */
function toTab(list) {
  const pad = list.length.toString(base).length;
  /** @type {Record<string,string>} */
  const res = {};
  let i = 0;
  res[NONE] = (i++).toString(base).padStart(pad, "0");
  for (const key of list) res[key] = (i++).toString(base).padStart(pad, "0");
  return res;
}

export const pseudos = toTab(pseudoList);
export const props = toTab(propList);
